export const NavTypes = {
  SET_LOG_LAT: "SET_LOG_LAT",
  CLEAR_LOG_LAT: "CLEAR_LOG_LAT",
  SET_DIMS: "SET_DIMS",
  SET_GRID: "SET_GRID",
  SET_HEATMAP_RANGE: "SET_HEATMAP_RANGE",
  MOD_CORD: "MOD_CORD",
  MOD_OVER_CORD: "MOD_OVER_CORD",
  RENDER_GRID: "RENDER_GRID",
  RENDER_HEATMAP: "RENDER_HEATMAP",
  FETCH_LOCATION_START: "FETCH_LOCATION_START",
  FETCH_LOCATION_SUCCESS: "FETCH_LOCATION_SUCCESS",
  FETCH_LOCATION_FAILURE: "FETCH_LOCATION_FAILURE"
};
